# Generated by Django 3.0.2 on 2020-01-30 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20200130_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('timeZone', models.CharField(blank=True, default='CEST', max_length=20, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('polygon', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revisionDate', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Farm Settings',
                'verbose_name_plural': 'Farms Settings',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmName', models.CharField(max_length=40, unique=True)),
                ('soil1', models.CharField(blank=True, max_length=40)),
                ('soil2', models.CharField(blank=True, max_length=40)),
                ('soil3', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
