# Generated by Django 3.0.2 on 2020-01-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_farmsettings_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
            ],
        ),
    ]
